# Generated by Django 6.0 on 2025-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='category',
            field=models.CharField(choices=[('3d', '3D-дизайн'), ('2d', '2D-дизайн'), ('sketch', 'Эскиз'), ('full', 'Полный дизайн-проект'), ('consult', 'Консультация')], default='sketch', max_length=20, verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
